// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeFinderBE.Migrations
{
    [DbContext(typeof(HomeFinderDbContext))]
    [Migration("20240529144825_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeFinderBE.Models.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("RoomID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Image = "https://9to5mac.com/wp-content/uploads/sites/6/2023/11/macbook-pro-space-black0000.jpg?quality=82&strip=all&w=1600",
                            Name = "Laptop",
                            RoomID = 1
                        },
                        new
                        {
                            ID = 2,
                            Image = "https://cdn.hswstatic.com/gif/power-drill-1.jpg",
                            Name = "Electric Drill",
                            RoomID = 2
                        },
                        new
                        {
                            ID = 3,
                            Image = "https://images.thdstatic.com/productImages/889823b6-5f7d-426b-b00a-a7f187b7c276/svn/flexzilla-garden-hoses-hfzg550yw-e-64_600.jpg",
                            Name = "Garden Hose",
                            RoomID = 2
                        },
                        new
                        {
                            ID = 4,
                            Image = "https://www.cnet.com/a/img/resize/63f281d1fc4aabccc520b46df58a31c209a92b59/hub/2017/05/10/6dd6d29e-422f-4d71-8793-9bfc1e1ce758/kitchenaidblender-1.jpg?auto=webp&fit=crop&height=1200&width=1200",
                            Name = "Blender",
                            RoomID = 3
                        },
                        new
                        {
                            ID = 5,
                            Image = "https://assets.adidas.com/images/w_600,f_auto,q_auto/fa54b166335a427fad65af9c00a736f9_9366/TERREX_Soulstride_Flow_Trail_Running_Shoes_Black_GX1822_01_standard.jpg",
                            Name = "Running Shoes",
                            RoomID = 1
                        });
                });

            modelBuilder.Entity("HomeFinderBE.Models.ItemTag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ItemID")
                        .HasColumnType("integer");

                    b.Property<int>("TagID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("ItemTags");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ItemID = 1,
                            TagID = 1
                        },
                        new
                        {
                            ID = 2,
                            ItemID = 2,
                            TagID = 2
                        },
                        new
                        {
                            ID = 3,
                            ItemID = 3,
                            TagID = 3
                        },
                        new
                        {
                            ID = 4,
                            ItemID = 4,
                            TagID = 4
                        },
                        new
                        {
                            ID = 5,
                            ItemID = 5,
                            TagID = 5
                        });
                });

            modelBuilder.Entity("HomeFinderBE.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Image = "https://hips.hearstapps.com/hmg-prod/images/ghk090123homefeature-005-655b97aee4cbc.jpg?crop=0.828xw:1.00xh;0,0&resize=980:*",
                            Name = "Bedroom",
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            Image = "https://www.realsimple.com/thmb/VeovlLwOeeZUweFGCdPA97yrNzc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/what-not-to-store-in-a-garage-GettyImages-528094494-61fda36cad814a338fba3cda15073163.jpg",
                            Name = "Garage",
                            UserID = 1
                        },
                        new
                        {
                            ID = 3,
                            Image = "https://www.ikea.com/ext/ingkadam/m/7d967a35b0d7f7fd/original/PH194740.jpg",
                            Name = "Kitchen",
                            UserID = 1
                        },
                        new
                        {
                            ID = 4,
                            Image = "https://www.houselogic.com/wp-content/uploads/2023/08/easy-clean-modern-bathroom-hero.jpg?crop&resize=2048%2C1365&quality=80",
                            Name = "Bathroom",
                            UserID = 1
                        },
                        new
                        {
                            ID = 5,
                            Image = "https://media.architecturaldigest.com/photos/62f3c04c5489dd66d1d538b9/16:9/w_2560%2Cc_limit/_Hall_St_0256_v2.jpeg",
                            Name = "Living Room",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("HomeFinderBE.Models.Tag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Tools"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Garden"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Kitchen"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("HomeFinderBE.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "Cody",
                            LastName = "Tucker"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
